url: http://localhost:3000/
secret: defaultSecret
deadline: "2014-08-03T18:00:00+01:00"
uploadDir: ./uploads # this should point to a Dropbox shared folder
maxFileSize: 20485760
allowedExtensions:
  - doc
  - docx